job_id: st_resnet

data:
  # Path to indexed HelioFM training and validation datasets
  train_data_path: /nobackupnfs1/sroy14/processed_data/Helio/aremerge_skasapis/train_indexed_data_ar_emergence_kasapis_rohit_norm.h5
  valid_data_path: /nobackupnfs1/sroy14/processed_data/Helio/aremerge_skasapis/test_indexed_data_ar_emergence_kasapis_rohit_norm.h5

  flare_label_type: "maximum"
  channels:
    - aia94
    - aia131
    - aia171
    - aia193
    - aia211
    - aia304
    - aia335
    - aia1600
    - hmi_bx
    - hmi_by
    - hmi_bz
    - hmi_m
    - hmi_v

  time_delta_input_minutes: [0]
  time_delta_target_minutes: +60
  batch_size: 512
  num_data_workers: 12
  prefetch_factor: null
  scalers_path: "../../HelioFM/configs/scale_signum_13chan_2011_2014.yaml"

model:
  model_type: spatio_temporal_resnet  # Options: [persistence, average]

  # Input configuration
  img_size: 4096
  patch_size: 16
  in_channels: 13

  # Time embedding configuration
  time_embedding:
    type: linear          # Options: linear, fourier, perceiver
    n_queries: null       # Required for perceiver
    time_dim: 1

  # UNet-style decoder config (if applicable)
  unet_embed_dim: null
  unet_blocks: null
  unet_concat_activations: false

  # Transformer parameters
  embed_dim: 1024
  depth: 8
  spectral_blocks: 4
  num_heads: 8
  mlp_ratio: 4.0
  rpe: false
  drop_rate: 0.0
  window_size: 2

  # Flow learning (optional)
  dp_rank: 4
  learned_flow: false
  epochs_to_learn_flow: 0
  init_weights: false
  checkpoint_layers: []

metrics:
  cdelt: 0.6
  rsun: 976.0
  limb_radius: 0.9
  distance_to_sun: 1.0

  train_loss_config:
    normalized_units:
      metrics: [mse:global]
      weights: [1.0]

  train_metrics_config:
    active_mask_config:
      reference_channel_for_active_mask: aia335
    normalized_units:
      metrics: [mse:global]

  validation_metrics_config:
    normalized_units:
      metrics: []
    natural_units:
      metrics: []

optimizer:
  warm_up_steps: 0
  max_epochs: 1000
  learning_rate: 0.01
  min_lr: 0.000001

use_latitude_in_learned_flow: false

# loss_weights: per-channel weights (if needed); empty list disables it
loss_weights: []

rollout_steps: 0
num_mask_aia_channels: 0
drop_hmi_probablity: 0.0

validate_after_epoch: 1
wandb_log_train_after: 100         # Must be < iters_per_epoch_train
wandb_project: "downstream"        # e.g., "helio-fm", "spectformer_with_metrics"

save_wt_after_iter: 100
path_experiment: checkpoints

iters_per_epoch_train: 500
iters_per_epoch_valid: 200

parallelism: "ddp"                 # Options: "ddp", "fsdp"
dtype: "float32"                   # Options: float32, float16, bfloat16
